### ISSUE TITLE
Little Question for you

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/TZF#25]
Hello there!
I know that u moved to other projects and stuff..
but there is one thing about this game that tackled me from beginning and even now with ur latest 1.3 fix.
We know that game hates gamepads especially non xbox gamepads..
so thats my problem.
After installing x360ce , which is a must.. otherwise keybinds are insanity and cant rebind shit properly
i get problem with custom_buttons.dds
half game becomes new ps3 buttons while other half is showing my logitech buttons............

i know that ur dds only replaces xbox buttons. BUT
can you make it to replace EVERY buttons?
even if its not xbox?

i can post picture of my dilemma if that can help making my request more clear
Thanks for listening.

**Comment by IceLancerSR** [comment]
This is picture what happens
http://imgur.com/creOQ5N
http://imgur.com/6ALsUB2
xbox is "virtual gamepad" from x360ce which is actually logitech mapped to xbox..
so now i get some buttons in game showing xbox buttons and others showing logitech.. hilarious

**Comment by Kaldaien** [comment]
Sorry, I don't have E-Mail notifications setup for GitHub. It's easiest for me if you ask me questions on a project I'm not working on anymore on Steam.

The game was designed for DirectInput, it just doesn't reliably use it. You can actually re-compile SDL and force the game to use DirectInput, that's something I really admire about the way the game was designed.

**Comment by IceLancerSR** [comment]
I dont have Micr visual C++ to recompile ur git "emergency fix"

**Comment by Kaldaien** [comment]
You don't need it, I pushed the fix out and then re-uploaded the build.

**Comment by IceLancerSR** [comment]
Ah i see! will test then! i saw 1 hour difference in release notes but didn't thought u might be updating file :P

**Comment by IceLancerSR** [comment]
Tested it.
Its still the same. But i guess its not something that u can fix
Game is constantly forcing detection of both virtual and direct controller and screwing buttons up..
